### ISSUE TITLE
about  I3D RGB +DMC-Net in table4 

### ISSUE THREAD

**Issue by 1234happy** [facebookresearch/dmc-net#3]
In the paper, you described I3D RGB +DMC-Net (I3D) improves I3D RGB via incorporating predictions from our DMC-Net (I3D).
I'd grateful if you could give more detail about how to fusing the two methods( I3D RGB  and DMC-Net (I3D) ).

**Comment by XudongLinthu** [comment]
We followed common practice. Train I3D RGB and DMC-Net(I3D) separately; sum the classification scores predicted by them at test time to get the fused score for classification.
