### ISSUE TITLE
about detail of the module

### ISSUE THREAD

**Issue by JoseponLee** [facebookresearch/dmc-net#6]
I wonder that the full architecture of DMC-Net includes four stream（res152 for iframe, res50 for mv and res, and the motion stream for generated flow），is that right?

**Comment by zhengshou** [comment]
Yes!

**Comment by JoseponLee** [comment]
thank you for your reply, could you help to provide the visualize code for motion vectors and residual? thank you very much!

**Comment by zhengshou** [comment]
I just adopted common viz tools for optical flow. You may search for these and can easily find them online.
